### ISSUE TITLE
Почитай про propTypes еще раз

### ISSUE THREAD

**Issue by DmitriiMelnikOnix** [OlegEf/Entry-assignment-to-internship-2020#3]
PropTypes проверяют только props который приходит в компонент, в нем нет смысла если все значения хранятся напрямую в компоненте.
Часть переменных можно вынести выше и прокидывать их в компоненты
Например
```
const LinkMenu = ({pseudo_element, fast_move}) => {
  return (
	<div className="row">
		<div className="margin">
			<p className="before">{pseudo_element}</p>
		</div>
		<div className="margin">
			<a href="#logo" className="margin">{fast_move}</a>
		</div>
	</div>
  );
};
```

А при рендере этого компонента
```
<LinkMenu pseudo_element={'псевдоэлемент'} fast_move={'быстрый переход logo'} />
```
Это сделает твои компоненты более универсальными

**Comment by OlegEf** [comment]
Благодарю, сейчас начну исправлять
