### ISSUE TITLE
Упрощенная запись стрелочных функций

### ISSUE THREAD

**Issue by DmitriiMelnikOnix** [OlegEf/Entry-assignment-to-internship-2020#4]
Простые функции можно записывать без return
Например
```
const sum = (a, b) => a + b
```
Точно так же можно делать и с компонентами
```
const LinkMenu = () => (
    <div>
      ...
    </div>
  )
```
Мелочь, но красивее

**Comment by OlegEf** [comment]
Начинаю понимать насколько это упрощает чтение кода
